blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/aankitroy/full-stack-ai-agent-mastery/discussions
    about: Ask questions, share ideas, and discuss the project with the community
  - name: 🎯 Discord Community
    url: https://discord.gg/your-discord
    about: Join our real-time chat for collaboration and support
  - name: 📧 Email Support
    url: mailto:contact@yourdomain.com
    about: Contact maintainers directly for private matters or partnership inquiries
  - name: 🔒 Security Issues
    url: mailto:security@yourdomain.com
    about: Report security vulnerabilities privately







